### ISSUE TITLE
Addition to script

### ISSUE THREAD

**Issue by remcodejong1** [Bram-diederik/budgetenergy-homeassistant-emailparser#2]
Hi,

I added some more to your script. You might also be interested in this.

Because I get multiple emails from Budget Energie, I added a subject criteria.
Also, the tariffs are now saved with the starting month and year before. This will load the correct tariffs to the current month.
I have attached the modified scripts as txt files

[prices_set.txt](https://github.com/Bram-diederik/budgetenergy-homeassistant-emailparser/files/11601295/prices_set.txt)
[parse_emails.txt](https://github.com/Bram-diederik/budgetenergy-homeassistant-emailparser/files/11601296/parse_emails.txt)

**Comment by Bram-diederik** [comment]
added in latest commit
